Updated code extract lambda function for Market Data
AIPI510/aipi510-fall24 pull request #239
Opened 2024-11-16 03:18 UTC by sganes21

- Added code to pass Stock Market API key as env variable
- Query various stock tags as data points
- Dump response into Json file

2024-11-16 22:29 UTC, haranku16 requested changes

2024-11-16 22:29 UTC, haranku16 commented on steps/extract.py
> +
Let's clean up these extra whitespaces

2024-11-16 22:29 UTC, haranku16 commented on steps/extract.py
> +    print(response.json())
We can remove this print statement

2024-11-16 22:29 UTC, haranku16 commented on steps/extract.py
> +    message = f"The value of MY_ENV_VAR is: {my_env_var}"
We don't need this variable anymore

2024-11-16 22:29 UTC, haranku16 commented on steps/extract.py
> +    my_env_var = os.environ.get('MARKETSTACK_API_KEY', 'default_value')
suggest to rename this variable to api_key

2024-11-17 03:51 UTC, sganes21 commented on steps/extract.py
> +
Removed in subsequent commit

2024-11-17 03:51 UTC, sganes21 commented on steps/extract.py
> +    print(response.json())
Removed in subsequent commit

2024-11-17 03:51 UTC, sganes21 commented on steps/extract.py
> +    message = f"The value of MY_ENV_VAR is: {my_env_var}"
Removed in subsequent commit

2024-11-17 03:51 UTC, sganes21 commented on steps/extract.py
> +    my_env_var = os.environ.get('MARKETSTACK_API_KEY', 'default_value')
Updated in subsequent commit

2024-11-17 03:52 UTC, haranku16 approved these changes
Looks good, thanks!

2024-11-17 03:52 UTC, merged