Updated transform.py
AIPI510/aipi510-fall24 pull request #241
Opened 2024-11-17 12:35 UTC by sganes21

- Added initial commit to transform, to parse .json and convert to panda dataframe
- Assumes that the 'data' key in the API response always contains a list of dictionaries, each representing a stock entry.
- Have not added error handling
- Have not tested yet

2024-11-17 17:02 UTC, haranku16 requested changes

2024-11-17 17:02 UTC, haranku16 commented on steps/transform.py
> +    df = transform_response()
We'll need to pass event to this function

2024-11-17 17:02 UTC, haranku16 commented on steps/transform.py
> +        'body': json.dumps('Lambda function executed successfully')
Instead of json.dumps, can you pass df.to_csv() as the body so that the CSV text gets passed to the next function?

2024-11-18 03:04 UTC, sganes21 reviewed
-passed event to transform_response function
-pass the entire CSV content as a string in the body of the Lambda function's response.
-added optional headers to the response to specify the content type as CSV and suggest a filename for download.

2024-11-18 03:39 UTC, haranku16 approved these changes
Looks good, thanks!

2024-11-18 03:39 UTC, merged